### ISSUE TITLE
run_results.json doesn't exits

### ISSUE THREAD

**Issue by viniciusnunest** [Hiflylabs/dbt-snowflake-artifacts#1]
I'm trying to use the package using dbt cloud, but I got this error: 

```
13:24:54  Encountered an error:
Database Error
  253006: File doesn't exist: ['target/run_results.json']
 ```

**Comment by tiborkusztos** [comment]
Hi @viniciusnunest ,

First of all, thanks for trying out our package!

I'd like to start with a few follow-up questions so I can get a clearer picture of your setup and the steps you've already completed.

By default, dbt creates the `run_results.json` file directly inside the `target` folder, but in some cases, it might be overwritten or located elsewhere. Could you check if the `run_results.json` file is located inside your dbt project's `target` folder?

After initializing the project, this `run_results.json` file should be created automatically after the first `dbt run` anyway.

If you didn’t skip this [dbt run command step](https://github.com/Hiflylabs/dbt_snowflake_artifacts?tab=readme-ov-file#first-run) in the documentation, the `run_results.json` file should already be created under that run, even in an empty project:
`dbt run-operation create_artifact_resources`

*Note that the macro was renamed in recent versions, so the documentation should be updated. But if you skipped this step, please try running the updated dbt command mentioned above.*

This should resolve your issue, but if you get past this step, make sure to create an environment variable in dbt Cloud for the `Snowflake contract rate` var and reference the correct target names, as this is required for successfully adding the most recent run results.

```yaml
vars:
  # Business-critical cost config
  snowflake_contract_rate: "{{ env_var('SNOWFLAKE_CONTRACT_RATE', 4) }}"
  target_dev: 'dev'  # Your target name in dev
  target_prod: 'prod'  # Your target name in prod

```
Looking forward to hearing back from you! And let me know if you have any further questions.
